# Generated by Django 4.1.2 on 2023-01-07 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, verbose_name='Complete Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject Message')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Contact List',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150, verbose_name='Complete Name')),
                ('address', models.CharField(max_length=150, verbose_name='Complete Address')),
                ('phone_number', models.CharField(default='+63', max_length=13, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Profile Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150, verbose_name='Complete Name')),
                ('address', models.CharField(max_length=150, verbose_name='Complete Address')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('dname', models.CharField(max_length=150, verbose_name='Driver Name/Operator Name')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone Address')),
                ('d_address', models.CharField(max_length=150, verbose_name='Driver/Operator Complete Address')),
                ('plate_number', models.CharField(max_length=50, verbose_name='Plate Number')),
                ('operator_number', models.CharField(default='+63', max_length=13, verbose_name='Operator Number')),
                ('accident_date', models.DateField(verbose_name='Date of Accident')),
                ('accident_time', models.TimeField(verbose_name='Time of Accident')),
                ('accident_place', models.CharField(max_length=150, verbose_name='Place of Accident')),
                ('violation_type', models.CharField(choices=[('Contracting Passenger', 'Contracting Passenger'), ('Overcharging Fare', 'Overcharging Fare'), ('Arrogant Discourteous Driver', 'Arrogant Discourteous Driver'), ('Refusal To Convey Passenger', 'Refusal To Convey Passenger'), ('Hit And Run', 'Hit And Run'), ('Threatening Passenger', 'Threatening Passenger'), ('Reckless Driving', 'Reckless Driving'), ('Discriminating Againts Passenger', 'Discriminating Againts Passenger'), ('Refusal To Grant Discount', 'Refusal To Grant Discount')], max_length=150, verbose_name='Violation Type')),
                ('complaint_description', models.TextField(verbose_name='Complaint Description')),
                ('complaint_evidence', models.ImageField(blank=True, null=True, upload_to='evidences', verbose_name='Evidence Image')),
                ('verification', models.CharField(choices=[('Accepted', 'Accepted'), ('Reviewing', 'Reviewing'), ('Declined', 'Declined')], default='Reviewing', max_length=100, verbose_name='Verification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Complaint List',
            },
        ),
    ]
